In [84]:
import torch
from torch import tensor
import numpy as np

# Tensors 

## Numeric

### Empty

In [85]:
t0 = torch.empty(2,2,2)

t0

tensor([[[-4.3165e+12,  3.0831e-41],
         [ 1.1210e-44,  0.0000e+00]],

        [[ 1.2612e-44,  0.0000e+00],
         [ 4.4721e+21,  1.5956e+25]]])

### Random

In [86]:
t00 = torch.rand(2,2)

t00

tensor([[0.5946, 0.4888],
        [0.9302, 0.6262]])

In [87]:
rvalues = torch.rand(2,2, dtype=torch.float64) # set the dtype

rvalues
print(rvalues.dtype)

torch.float64


### Zeros

In [88]:
zeros = torch.zeros(2,2)

zeros 

tensor([[0., 0.],
        [0., 0.]])

### Ones

In [89]:
ones = torch.ones(2,2)

ones

tensor([[1., 1.],
        [1., 1.]])

In [90]:
t1 = tensor(4.)

print(t1.dtype)
print(type(t1))

torch.float32
<class 'torch.Tensor'>


## Vector

In [91]:
# Create a vector 
t2 = tensor([1,2,3,4,5])

print(t2.dtype)
print(type(t2))

torch.int64
<class 'torch.Tensor'>


### Accessing

In [92]:
print(t2[2]) # Accessing items


print(t2[0:3]) # Slicing


print(t2[-1]) # last item

scaler = t2[1].item() # returns the value of this tensor as a standard Python number.

print(type(scaler))

tensor(3)
tensor([1, 2, 3])
tensor(5)
<class 'int'>


## Matrix

In [93]:
t3 = tensor([[1,2],[3,4],[5,6]])

print(t3.dtype)
print(type(t3))

t3

torch.int64
<class 'torch.Tensor'>


tensor([[1, 2],
        [3, 4],
        [5, 6]])

## 3D array

In [94]:
t4 = tensor([[[1,2],[3,4]],[[5,6],[7,8]]])


print(t4.dtype)
print(type(t4))

t4

torch.int64
<class 'torch.Tensor'>


tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

## Checking Tensors Shapes

In [95]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [96]:
print(t2)
t2.shape

tensor([1, 2, 3, 4, 5])


torch.Size([5])

In [97]:
print(t3)
t3.shape

tensor([[1, 2],
        [3, 4],
        [5, 6]])


torch.Size([3, 2])

In [98]:
print(t4)
t4.shape

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


torch.Size([2, 2, 2])

# Tensor operations and gradients

In [99]:
x = tensor(4., requires_grad=True)
w = tensor(5., requires_grad=True)
z = tensor(4., requires_grad=True)

In [100]:
# Arithmetic Operation

a = x * w + z

a

tensor(24., grad_fn=<AddBackward0>)

In [101]:
# Compute Derivatives
a.backward()

In [102]:
# Display Gradients 
print("dy/dx:",x.grad)
print("dy/dw:",w.grad)
print("dy/dz:",z.grad)

dy/dx: tensor(5.)
dy/dw: tensor(4.)
dy/dz: tensor(1.)


In [103]:
r = tensor([1,2,3])
q = tensor([4,5,6])

m = r + q 

print(m)
print(torch.add(r,q))

tensor([5, 7, 9])
tensor([5, 7, 9])


In [104]:
r = tensor([1,2,3])
q = tensor([4,5,6])

m = r - q 

print(m)
print(torch.subtract(r,q))

tensor([-3, -3, -3])
tensor([-3, -3, -3])


In [105]:
r = tensor([1,2,3])
q = tensor([4,5,6])

# Basic Arithmetics 
print(torch.add(r,q))
print(torch.subtract(r,q))
print(torch.multiply(r,q))
print(torch.divide(r,q))

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])


In [106]:
# add value to each item 

z = r.add(3)
print(r)
print(z)

z = r.add_(3) # will change the values of the r tensor as well
print(r)
print(z)

tensor([1, 2, 3])
tensor([4, 5, 6])
tensor([4, 5, 6])
tensor([4, 5, 6])


# Convert a Numpy array to Pytorch Tensor

In [107]:
arr = np.array([1,2,3,4])

x = torch.from_numpy(arr)

print(arr.dtype)
print(type(arr))

print(x.dtype)
print(type(x))

int64
<class 'numpy.ndarray'>
torch.int64
<class 'torch.Tensor'>


#Convert a Pytorch Tensor to Numpy array

In [108]:
to_numpy = x.numpy()

print(to_numpy.dtype)
print(type(to_numpy))

int64
<class 'numpy.ndarray'>
