In [1]:
import torch 

In [2]:
x = torch.randn(3, requires_grad = True)

In [3]:
f = x + 2 

print(f) 

tensor([2.4019, 2.1686, 2.1717], grad_fn=<AddBackward0>)


In [4]:
g = f*f*2
print(g)

tensor([11.5384,  9.4056,  9.4326], grad_fn=<MulBackward0>)


In [5]:
h = g.mean()
print(h)

tensor(10.1256, grad_fn=<MeanBackward0>)


In [6]:
h.backward() # dh/dx

In [7]:
print(x.grad)

tensor([3.2026, 2.8915, 2.8956])


In [8]:
value = float(input("Please give a value:"))

Please give a value:2


In [9]:
# function 
# f(x) = 5x⁴ + 3x³ + 7x² + 9x -5 

In [10]:
x = torch.autograd.Variable(torch.Tensor([value]), requires_grad=True)

y = 5*x**4 + 3*x**3 + 7*x**2 + 9*x - 5

y.backward()
x.grad

tensor([233.])